env:
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:sonarjs/recommended
plugins:
    - simple-import-sort
parserOptions:
    ecmaVersion: latest
    ecmaFeatures:
        impliedStrict: true
    sourceType: module
rules:
    indent:
        - error
        - 4
        - SwitchCase: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
overrides:
    - files: "**/*.ts"
      extends:
          - eslint:recommended
          - plugin:@typescript-eslint/recommended
          - plugin:sonarjs/recommended
      rules:
          indent: off
